import mongoose from "mongoose";

/*A customer has:
* id: a string generated by stripe
* firstName: The customer's first name
* lastName: The customer's last name
* cards: An array of the stripe IDs of credit cards
* orders: an array of order IDs linked to the customer.
* notes: any direct notes a customer has. This could potentially become an array with its own schema later.
* allergies: an array of strings that correspond to someones allergies.
* * */
export const userSchema = new mongoose.Schema({
    userID: String,
    name: String,
    email: String,
    password: String,
    role: String, //todo: ENUM
    tokenVersion: Number,
})

export const userModel = mongoose.model('User', userSchema);


export const customerSchema = new mongoose.Schema({
    ...userSchema.obj,
    name: String,
    cards: [String],
    orders: [String],
    notes: String,
    allergies: [String],
})

export const customerModel = mongoose.model('Customer', customerSchema);

module.exports = {customerModel, userModel};